import {PROVIDERS,PRODUCTS,safeURL,bboxValue,searchRequest,fetchJSON,nextRequest,uniqueFeatures,validateFeatures} from './protocol.mjs';
const $=id=>document.getElementById(id);
const contexts={mumbai:[72.63,18.88,73.13,19.28],beira:[34.59,-20.03,35.09,-19.63],durban:[30.77,-30.06,31.27,-29.66],mombasa:[39.42,-4.24,39.92,-3.84],lusaka:[28.03,-15.59,28.53,-15.19],kampala:[32.33,.15,32.83,.55],lagos:[3.13,6.32,3.63,6.72]};
const snapshotInfo={copernicus_mumbai:{context:'mumbai',label:'Copernicus Sentinel-2 scene metadata',note:'Surface reflectance scenes are not measurements of air temperature, disease, or facility exposure.'},dea_beira:{context:'beira',label:'Digital Earth Africa annual WOfS metadata',note:'WOfS summarizes wet observations among clear Landsat observations. It is not flood probability, drinking-water quality, or a measured flood depth.'},allen_mombasa:{context:'mombasa',label:'Allen Coral Atlas mapped habitat polygons',note:'These eight habitat polygons are a bounded teaching extract. Habitat classes describe mapped substrate; they do not establish current bleaching, reef health, fish catch, or clinical outcomes.'}};
const map=L.map('evidence-map',{worldCopyJump:false}).setView([19.08,72.88],9);
map.attributionControl.setPrefix('Leaflet');
map.attributionControl.addAttribution('Made with Natural Earth');
let sceneLayer=L.geoJSON(null,{style:{color:'#14796c',weight:2,fillOpacity:.16},onEachFeature:(f,l)=>l.on('click',()=>inspect(f))}).addTo(map);
let areaLayer=L.layerGroup().addTo(map),facilityLayer=L.layerGroup().addTo(map);
let loaded=null,facilityData=null,busy=false,sources=[];
function commitDataset(candidate){
 validateFeatures(candidate.features);
 const previous=loaded;
 try{loaded=candidate;render();}
 catch(error){loaded=previous;if(previous)render();throw error;}
}
function el(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function link(text,url){const a=el('a',text);try{a.href=safeURL(url);a.target='_blank';a.rel='noopener';}catch{a.removeAttribute('href');}return a;}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function buttons(){for(const e of document.querySelectorAll('#search-form button'))e.disabled=busy;$('next').disabled=busy||!loaded?.next||loaded.pages>=3||loaded.features.length>=24;$('export').disabled=busy||!loaded;}
async function working(fn){if(busy)return;busy=true;buttons();try{await fn();}catch(e){status(`${e.message} Your last successfully loaded evidence remains below.`,true);}finally{busy=false;buttons();}}
function updateCollections(){const p=PROVIDERS[$('provider').value];$('collection').replaceChildren(...p.collections.map(([v,t])=>{const o=el('option',t);o.value=v;return o;}));if($('provider').value==='dea'){$('context').value='beira';$('start').value='2022-01-01';$('end').value='2022-12-31';}else{$('start').value='2024-04-01';$('end').value='2024-04-30';}updateContext();}
function updateContext(){$('bbox').value=contexts[$('context').value].join(',');}
$('provider').addEventListener('change',updateCollections);$('context').addEventListener('change',updateContext);
function itemTitle(f){return String(f.properties?.class_name??f.properties?.class??f.properties?.habitat??f.id??'Unnamed item');}
function date(f){const p=f.properties||{};return p.start_datetime&&p.end_datetime&&p.start_datetime!==p.end_datetime?`${p.start_datetime} / ${p.end_datetime}`:p.datetime||p.start_datetime||p.end_datetime||'Not supplied';}
function cloud(f){const v=f.properties?.['eo:cloud_cover'];return typeof v==='number'&&Number.isFinite(v)?`${v.toFixed(1)}%`:'Not supplied';}
function render(){sceneLayer.clearLayers();areaLayer.clearLayers();sceneLayer.addData({type:'FeatureCollection',features:loaded.features});const bbox=loaded.provenance.query?.bbox;
 if(bbox)L.rectangle([[bbox[1],bbox[0]],[bbox[3],bbox[2]]],{color:'#b27a18',weight:2,fillOpacity:0,dashArray:'5 5'}).addTo(areaLayer);
 const bounds=sceneLayer.getBounds();if(bounds.isValid())map.fitBounds(bounds.pad(.15),{maxZoom:13});else if(bbox)map.fitBounds([[bbox[1],bbox[0]],[bbox[3],bbox[2]]]);
 $('results').replaceChildren();for(const f of loaded.features){const row=el('tr');row.append(el('td',itemTitle(f)),el('td',date(f)),el('td',cloud(f)));const td=el('td'),b=el('button','Inspect');b.type='button';b.addEventListener('click',()=>inspect(f));td.append(b);row.append(td);$('results').append(row);}
 $('result-caption').textContent=`${loaded.label} — ${loaded.features.length} loaded items`;
 $('loaded-query').textContent=`${loaded.provenance.mode}. ${loaded.provenance.provider}. ${loaded.provenance.retrieved_on||loaded.provenance.retrieved_at}. ${loaded.provenance.license}. Query: ${JSON.stringify(loaded.provenance.query||loaded.provenance.scope)}.`;
 $('interpretation').textContent=loaded.note;$('detail').replaceChildren(el('h2','Inspect an item'),el('p',loaded.features.length?'Select a footprint or table row for details.':'No matching evidence was returned. Broaden the dates or choose a different collection.'));
 renderFacilities();buttons();
}
function inspect(f){const box=$('detail');box.replaceChildren(el('h2',itemTitle(f)),el('p',`Collection: ${f.collection||'Allen Coral Atlas benthic habitat'} · Date: ${date(f)} · Cloud: ${cloud(f)}`));
 box.append(el('p',`${loaded.provenance.provider} · ${loaded.provenance.license}`));if(loaded.provenance.license_url)box.append(link('License and source terms',loaded.provenance.license_url));
 const props=el('details');props.append(el('summary','Product properties'),el('pre',JSON.stringify(f.properties||{},null,2)));box.append(props);
 const assetList=el('ul');for(const [name,a] of Object.entries(f.assets||{})){const li=el('li');li.append(link(a.title||name,a.href));li.append(document.createTextNode(` — ${a.type||'media type not stated'}; roles: ${(a.roles||[]).join(', ')||'not stated'}`));try{safeURL(a.href);}catch{li.append(el('code',` ${a.href}`));}assetList.append(li);}if(assetList.children.length){box.append(el('h3','Asset references'),el('p','Links describe provider assets. Some require an account or a separate download workflow. Large rasters are not loaded here.'),assetList);}
 const sourceLinks=el('p');for(const l of (f.links||[]).filter(l=>['self','license','collection'].includes(l.rel))){sourceLinks.append(link(l.rel,l.href),document.createTextNode(' · '));}box.append(sourceLinks);
 const bounds=L.geoJSON(f).getBounds();if(bounds.isValid())map.fitBounds(bounds.pad(.2),{maxZoom:14});
}
function renderFacilities(){facilityLayer.clearLayers();if(!$('facilities').checked||!facilityData)return;const context=loaded?.context||$('context').value;for(const f of facilityData.features.filter(f=>f.properties.case_id===context)){const p=f.properties,body=el('div');body.append(el('strong',p.name||'Unnamed mapped facility'),el('p',`${p.amenity||p.healthcare||'Health facility'} · archived OSM node, current operation unverified`),link('OpenStreetMap feature',p.osm_url));L.circleMarker([f.geometry.coordinates[1],f.geometry.coordinates[0]],{radius:5,color:'#7746a0',fillOpacity:.8,weight:1}).bindPopup(body).addTo(facilityLayer);}map.attributionControl.addAttribution('© OpenStreetMap contributors / Healthsites.io, ODbL 1.0');}
$('facilities').addEventListener('change',renderFacilities);
async function snapshot(name){await working(async()=>{status('Loading packaged evidence…');const r=await fetch(`../data/stac_${name}.json`);if(!r.ok)throw new Error('Packaged file is unavailable.');const d=await r.json(),info=snapshotInfo[name];const features=uniqueFeatures(validateFeatures(d.feature_collection.features));const candidate={features,context:info.context,label:info.label,note:info.note,pages:1,next:null,provenance:{...d.provenance,mode:'Packaged snapshot',query:d.provenance.request?{...d.provenance.request,bbox:bboxValue(d.provenance.request.bbox)}:null}};$('context').value=info.context;updateContext();commitDataset(candidate);status(`Loaded ${features.length} actual metadata / habitat records from a packaged snapshot. No live search was made.`);});}
for(const b of document.querySelectorAll('[data-snapshot]'))b.addEventListener('click',()=>snapshot(b.dataset.snapshot));
$('search-form').addEventListener('submit',e=>{e.preventDefault();working(async()=>{const selectedContext=$('context').value;const request=searchRequest({provider:$('provider').value,collection:$('collection').value,bbox:$('bbox').value,start:$('start').value,end:$('end').value});status('Searching the public catalog…');const d=await fetchJSON(request),p=PROVIDERS[request.provider],product=PRODUCTS[request.query.collections[0]];const next=nextRequest(d,request);const candidate={features:uniqueFeatures(validateFeatures(d.features)),context:selectedContext,label:`${p.name} ? ${product.title} live metadata`,note:product.note,pages:1,next,request,provenance:{provider:p.name,mode:'Live catalog query',retrieved_at:new Date().toISOString(),query:request.query,source_url:request.url,license:p.license,license_url:product.licenseURL||p.licenseURL,attribution:product.attribution,requests:[{url:request.url,method:request.method}]}};commitDataset(candidate);status(`Loaded ${loaded.features.length} items from the live catalog. Footprints do not show health impacts.`);});});
$('next').addEventListener('click',()=>working(async()=>{if(!loaded?.next)return;status('Loading another page from the same query…');const request=loaded.next,d=await fetchJSON(request),next=nextRequest(d,request);const candidate={...loaded,features:uniqueFeatures([...loaded.features,...validateFeatures(d.features)]),next,pages:loaded.pages+1,provenance:{...loaded.provenance,requests:[...loaded.provenance.requests,{url:request.url,method:request.method,...(request.body?{body:request.body}:{})}]}};commitDataset(candidate);status(`${loaded.features.length} unique items loaded across ${loaded.pages} pages. This explorer stops after three pages or 24 items.`);}));
$('export').addEventListener('click',()=>{if(!loaded)return;const blob=new Blob([JSON.stringify({type:'FeatureCollection',features:loaded.features,provenance:loaded.provenance},null,2)],{type:'application/geo+json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='climate-health-evidence.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
function renderLibrary(){const term=$('source-search').value.trim().toLowerCase(),theme=$('theme').value;const chosen=sources.filter(s=>(theme==='all'||s.themes.includes(theme))&&JSON.stringify(s).toLowerCase().includes(term));$('library-count').textContent=`${chosen.length} of ${sources.length} sources · checked 9 October 2026`;$('source-cards').replaceChildren();for(const s of chosen){const c=el('article',undefined,'source-card');c.id=s.id;c.append(el('p',s.kind,'eyebrow'),el('h3',s.title),el('p',s.description),el('p',`Access: ${s.access}`),el('p',`Rights: ${s.license}`),el('p',s.caveat,'note'));const links=el('p');for(const [name,url] of Object.entries(s.links))links.append(link(name,url),document.createTextNode(' · '));c.append(links,el('p',`Citation: ${s.citation}`,'hint'));$('source-cards').append(c);}}
$('source-search').addEventListener('input',renderLibrary);$('theme').addEventListener('change',renderLibrary);
await Promise.allSettled([
 fetch('../data/natural-earth-land.geojson').then(r=>{if(!r.ok)throw Error('Land unavailable');return r.json();}).then(d=>L.geoJSON(d,{style:{color:'#bac8bc',weight:.5,fillColor:'#e1e9df',fillOpacity:1},interactive:false}).addTo(map).bringToBack()).catch(()=>status('Background land unavailable; evidence footprints can still load.',true)),
 fetch('../data/healthsites_facilities.geojson').then(r=>r.json()).then(d=>{facilityData=d;renderFacilities();}).catch(()=>{$('facilities').disabled=true;}),
 fetch('sources.json').then(r=>{if(!r.ok)throw Error('Source library unavailable');return r.json();}).then(d=>{sources=d.sources;const themes=[...new Set(sources.flatMap(s=>s.themes))].sort();for(const t of themes){const o=el('option',t);o.value=t;$('theme').append(o);}renderLibrary();}).catch(e=>{$('library-count').textContent=e.message;})
]);
await snapshot('copernicus_mumbai');
