import {scenario} from './model.js';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={view:'map',case:'mumbai',heat:1.5,water:.6,adaptation:'baseline',layer:'capacity',step:0,zoom:1};
let cases,adaptations,land,healthsites=null,plotRevision=0;
const tour=[
 {title:'Begin with the evidence',case:'mumbai',heat:1.5,water:.6,adaptation:'baseline',text:'NASA records a global annual warming signal. This map instead contains invented facility scenarios at approximate city anchors. A global anomaly does not measure local heat exposure. India is part of our learning pathway; no marker indicates actual PEPFAR funding.'},
 {title:'A dry clinic can lose its route',case:'beira',heat:1.5,water:.8,adaptation:'baseline',text:'The invented road threshold is lower than the clinic floor. Move the coastal water slider and watch access change. This is a datum-and-dependency exercise: tides, waves, drainage and hydrologic connection are absent.'},
 {title:'Find the service bottleneck',case:'lusaka',heat:2.5,water:.6,adaptation:'sponge',text:'This inland case has no marine exposure in the model. Water harvesting adds supply, but limited electricity can still constrain the result. HIV/TB continuity requires locally designed referral, medicine-supply, staffing and privacy safeguards.'},
 {title:'Compare a portfolio of responses',case:'mombasa',heat:2,water:1.2,adaptation:'combined',text:'Combine shade, water capture, raised access and backup power under explicit fictional effects. Mangroves, seagrass, wetlands and healthy reefs can have contextual co-benefits, but this model assigns them no universal flood-protection factor.'},
 {title:'Make a claim you can defend',case:'lagos',heat:2,water:.9,adaptation:'engineering',text:'Export the assumptions and a story project. Discuss displacement, host-community needs, food and water access, conflict context and equity without inventing disease or conflict forecasts. State what observation would change your conclusion.'}
];
async function json(path){const r=await fetch(path);if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return r.json();}
function selected(){return cases.find(c=>c.id===state.case);}
function results(){return cases.map(c=>scenario(c,state.heat,state.water,state.adaptation,adaptations));}
function color(r){if(state.layer==='access')return r.access_open?'#177a66':'#c46535';if(state.layer==='heat')return r.indoor_c>=35?'#bb6039':'#cfab58';return r.capacity>=70?'#247b68':r.capacity>=40?'#b49a50':'#b6573d';}
function markerValue(r){return state.layer==='heat'?`${r.indoor_c.toFixed(1)} °C`:state.layer==='access'?(r.access_open?'Open':'Closed'):`${r.capacity} visits`;}
function svgEl(tag,attrs={},text){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e;}
function facilityFeatures(){return healthsites?.features.filter(f=>f.properties.case_id===state.case)||[];}
function mapBounds(){if(state.layer==='healthsites'){const c=selected();return[c.longitude-.25,c.latitude-.20,c.longitude+.25,c.latitude+.20];}let b=[-22,-39,101,41];if(state.zoom>1){const c=selected(),w=123/state.zoom,h=80/state.zoom;b=[c.longitude-w/2,c.latitude-h/2,c.longitude+w/2,c.latitude+h/2];}return b;}
function renderMap(rows){const svg=$('map'),focusedCase=svg.contains(document.activeElement)?document.activeElement.dataset.case:null;svg.replaceChildren();const b=mapBounds(),p=([x,y])=>[35+(x-b[0])/(b[2]-b[0])*930,455-(y-b[1])/(b[3]-b[1])*420];const defs=svgEl('defs'),clip=svgEl('clipPath',{id:'map-clip'});clip.append(svgEl('rect',{x:0,y:0,width:1000,height:490}));defs.append(clip);svg.append(defs);const g=svgEl('g',{'clip-path':'url(#map-clip)'});svg.append(g);
 for(const f of land.features){const polys=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];for(const poly of polys){const d=poly.map(ring=>ring.map((c,i)=>`${i?'L':'M'}${p(c).map(n=>n.toFixed(2)).join(',')}`).join(' ')+'Z').join(' ');g.append(svgEl('path',{d,fill:'#d7e2d6',stroke:'#a3b7ab','stroke-width':.8,'fill-rule':'evenodd'}));}}
 if(state.layer!=='healthsites'){for(let lon=-20;lon<=100;lon+=20){const [x]=p([lon,0]);g.append(svgEl('path',{d:`M${x} 0V490`,stroke:'#92a6a8','stroke-opacity':.18}));}cases.forEach((c,i)=>{const r=rows[i],[x,y]=p([c.longitude,c.latitude]),group=svgEl('g',{role:'button',tabindex:0,'data-case':c.id,'aria-label':`${c.city}, ${c.country}, synthetic ${markerValue(r)}`});group.append(svgEl('circle',{cx:x,cy:y,r:c.id===state.case?13:9,fill:color(r),stroke:c.id===state.case?'#183f43':'white','stroke-width':c.id===state.case?3:2}));group.append(svgEl('text',{x:x+17,y:y-5,fill:'#173f43','font-size':13,'font-weight':650,stroke:'#eaf1f1','stroke-width':3,'paint-order':'stroke'},c.city));group.append(svgEl('text',{x:x+17,y:y+12,fill:'#345','font-size':10,stroke:'#eaf1f1','stroke-width':3,'paint-order':'stroke'},markerValue(r)));const choose=()=>{state.case=c.id;$('case').value=c.id;update();};group.addEventListener('click',choose);group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}});g.append(group);});}
 else if(healthsites){facilityFeatures().forEach(f=>{if(f.geometry?.type!=='Point')return;const [x,y]=p(f.geometry.coordinates),m=svgEl('circle',{cx:x,cy:y,r:3.4,fill:'#376a98',stroke:'#fff','stroke-width':.7});m.append(svgEl('title',{},`${f.properties.name||'Unnamed mapped facility'} · archived Healthsites/OSM; no risk values`));g.append(m);});}
 svg.append(svgEl('text',{x:20,y:478,fill:'#446669','font-size':11},state.layer==='healthsites'?'Archived Healthsites / © OpenStreetMap contributors · ODbL · approximate map view':'Made with Natural Earth · WGS84 longitude/latitude · fictional city-anchor scenarios'));
 if(focusedCase)svg.querySelector(`[data-case="${focusedCase}"]`)?.focus();
}
function cuboid(x,y,z,w,d,h,fill,name){const X=[x,x+w,x+w,x,x,x+w,x+w,x],Y=[y,y,y+d,y+d,y,y,y+d,y+d],Z=[z,z,z,z,z+h,z+h,z+h,z+h];return{type:'mesh3d',x:X,y:Y,z:Z,i:[0,0,4,4,0,0,1,1,2,2,3,3],j:[1,2,5,6,1,5,2,6,3,7,0,4],k:[2,3,6,7,5,4,6,5,7,6,4,7],color:fill,opacity:.95,name,hovertemplate:`${escape(name)}<extra></extra>`,flatshading:true,showscale:false};}
function hasWebGL(){if(new URLSearchParams(location.search).get('webgl')==='off')return false;try{const c=document.createElement('canvas');return !!(c.getContext('webgl2')||c.getContext('webgl'));}catch{return false;}}
function sceneTraces(c,r){const data=[cuboid(-5,-5,-.4,10,10,.4,'#c8d4b6','Conceptual ground; not a DEM'),cuboid(-2,-1,c.floor_m,3,2,1.7,'#f1ddba',`Fictional clinic; floor ${c.floor_m} m above invented datum`),cuboid(-2.15,-1.15,c.floor_m+1.7,3.3,2.3,.18,'#458574','Clinic roof'),cuboid(-.1,-5,r.road_m,1,10,.12,'#838c8d',`Road elevation ${r.road_m.toFixed(2)} m`),cuboid(-2,-1,0,3,2,c.floor_m,'#a6a894','Clinic platform')];
 if(c.coastal)data.push({type:'mesh3d',x:[-5,5,5,-5],y:[-5,-5,5,5],z:Array(4).fill(state.water),i:[0,0],j:[1,2],k:[2,3],color:'#429cba',opacity:.45,name:'Conceptual water plane',hovertemplate:`Water ${state.water.toFixed(2)} m above invented datum<extra></extra>`});
 if(state.adaptation==='shade'||state.adaptation==='sponge'||state.adaptation==='combined'){for(const x of[-3,3]){data.push(cuboid(x,2,0,.17,.17,2,'#906941','Conceptual tree trunk'));data.push({type:'scatter3d',x:[x],y:[2],z:[2.5],mode:'markers',marker:{size:24,color:'#397659',opacity:.85},name:'Shade canopy (conceptual)',hoverinfo:'name'});}}
 data.push({type:'scatter3d',x:[-.5,.4,-4],y:[0,-3,-4],z:[c.floor_m+2.5,r.road_m+.35,Math.max(state.water,.2)+.5],mode:'text',text:['FICTIONAL CLINIC','ACCESS ROUTE',c.coastal?'WATER PLANE':'INLAND CONTEXT'],textfont:{size:10,color:'#163f43'},hoverinfo:'skip',showlegend:false});return data;}
function mapTraces(rows){const xs=[],ys=[],zs=[];for(const f of land.features){const polys=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];for(const poly of polys)for(const ring of poly){for(const p of ring){xs.push(p[0]);ys.push(p[1]);zs.push(0);}xs.push(null);ys.push(null);zs.push(null);}}const traces=[{type:'scatter3d',mode:'lines',x:xs,y:ys,z:zs,line:{color:'#91a898',width:2},hoverinfo:'skip',showlegend:false}];cases.forEach((c,i)=>{const r=rows[i],height=state.layer==='heat'?r.indoor_c:state.layer==='access'?(r.access_open?1:0):r.capacity;traces.push(cuboid(c.longitude-1,c.latitude-1,0,2,2,height,color(r),`${c.city}: synthetic ${markerValue(r)}`));});traces.push({type:'scatter3d',mode:'text',x:cases.map(c=>c.longitude),y:cases.map(c=>c.latitude),z:rows.map(r=>state.layer==='heat'?r.indoor_c+2:state.layer==='access'?1.15:r.capacity+8),text:cases.map(c=>c.city),textfont:{size:11,color:'#163f43'},hoverinfo:'skip',showlegend:false});return traces;}
async function render3D(rows,version){if(!hasWebGL()||!window.Plotly){$('plot').hidden=true;$('map').toggleAttribute('hidden',false);renderMap(rows);$('view-status').textContent='3D rendering is unavailable. The 2D map, exact table, controls and downloads remain usable. No external tiles are required.';return;}
 $('map').toggleAttribute('hidden',true);$('plot').hidden=false;const c=selected(),r=rows.find(r=>r.case_id===c.id),isScene=state.view==='scene',zTitle=isScene?'Elevation (m, invented datum)':state.layer==='heat'?'Synthetic indoor °C':state.layer==='access'?'Access: 1 open; 0 closed':'Synthetic visits / day';
 const scene={xaxis:{title:{text:isScene?'Schematic east (m)':'Longitude (degrees)'},range:isScene?[-5.5,5.5]:[-22,100]},yaxis:{title:{text:isScene?'Schematic north (m)':'Latitude (degrees)'},range:isScene?[-5.5,5.5]:[-38,40]},zaxis:{title:{text:zTitle},range:isScene?[0,6]:state.layer==='heat'?[0,45]:state.layer==='access'?[0,1.5]:[0,160]},aspectmode:'manual',aspectratio:{x:1.6,y:1.1,z:.65},camera:{eye:{x:1.5,y:-1.8,z:1.2}},dragmode:'orbit'};
 try{await Plotly.react($('plot'),isScene?sceneTraces(c,r):mapTraces(rows),{margin:{l:0,r:0,t:0,b:0},paper_bgcolor:'#f5f8f3',showlegend:false,scene,uirevision:`${state.view}-${state.layer}`,font:{family:'Segoe UI, Arial',color:'#163f43'}},{responsive:true,displaylogo:false,scrollZoom:true,modeBarButtonsToRemove:['toImage']});if(version===plotRevision)$('view-status').textContent='Drag to orbit in 3D. Scroll to zoom; use the modebar to reset the camera. Exact values and an accessible table are below. Geometry is schematic and vertical scales are exaggerated.';}catch(e){if(version!==plotRevision)return;$('plot').hidden=true;$('map').toggleAttribute('hidden',false);renderMap(rows);$('view-status').textContent='3D renderer could not start; the 2D map and table remain available.';}
}
function table(rows){if(state.layer==='healthsites'&&!healthsites){$('data-table').innerHTML='<table><caption>Archived Healthsites facilities</caption><tbody><tr><td>Facility data unavailable. Reload to retry; no facility records or scenario results are shown.</td></tr></tbody></table>';return;}if(state.layer==='healthsites'&&healthsites){$('data-table').innerHTML=`<table><caption>Archived mapped facilities · Healthsites / OpenStreetMap · no scenario values</caption><thead><tr><th>Name</th><th>Type</th><th>Longitude</th><th>Latitude</th></tr></thead><tbody>${facilityFeatures().map(f=>`<tr><td>${escape(f.properties.name||'Unnamed')}</td><td>${escape(f.properties.amenity||f.properties.healthcare||f.properties.type||'Facility')}</td><td>${Number(f.geometry.coordinates[0]).toFixed(5)}</td><td>${Number(f.geometry.coordinates[1]).toFixed(5)}</td></tr>`).join('')}</tbody></table>`;return;}
 $('data-table').innerHTML=`<table><caption>Synthetic results · same assumptions in map and table · one fictional day</caption><thead><tr><th>City context</th><th>Country</th><th>Indoor °C</th><th>Coastal access</th><th>Capacity / visits</th><th>Unmet visits</th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.case_id===state.case?'selected':''}"><td>${escape(r.city)}</td><td>${escape(r.country)}</td><td>${r.indoor_c.toFixed(1)}</td><td>${cases.find(c=>c.id===r.case_id).coastal?(r.access_open?'Open':'Closed'):'Not marine-exposed'}</td><td>${r.capacity}</td><td>${r.unmet_visits}</td></tr>`).join('')}</tbody></table>`;}
function renderComparison(){const c=selected(),rows=Object.keys(adaptations).map(a=>scenario(c,state.heat,state.water,a,adaptations));$('compare').innerHTML=`<p><strong>${escape(c.city)} · synthetic one-day capacity</strong></p>${rows.map(r=>`<div class="compare-row"><span>${escape(adaptations[r.adaptation].label)}<br><small>${r.cost_units} arbitrary cost units</small></span><div class="bar"><span style="width:${r.capacity/c.daily_visits*100}%"></span></div><strong>${r.capacity} visits</strong></div>`).join('')}<p class="hint">Bar length uses a common maximum of ${c.daily_visits} invented visits. Costs are not currency or procurement estimates. Equity, maintenance and local suitability need separate assessment.</p>`;}
function syncControls(){for(const id of['case','layer','adaptation'])$(id).value=state[id];$('heat').value=state.heat;$('water').value=state.water;}
function update(){const version=++plotRevision;try{if(state.layer==='healthsites')state.view='map';const rows=results(),c=selected(),r=rows.find(r=>r.case_id===c.id);$('heat-value').textContent=`${state.heat.toFixed(1)} °C`;$('water-value').textContent=`${state.water.toFixed(2)} m`;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',b.dataset.view===state.view));
 const real=state.layer==='healthsites';for(const id of ['csv','story-export'])$(id).disabled=real&&!healthsites;$('data-tag').textContent=real?'ARCHIVED HEALTHSITES / OSM ? OPERATION UNVERIFIED':'SYNTHETIC TEACHING SCENARIOS ? NOT FORECASTS';for(const id of ['heat','water','adaptation'])$(id).disabled=real;document.querySelectorAll('[data-view]').forEach(b=>b.disabled=real&&b.dataset.view!=='map');$('csv').textContent=real?'Download facility CSV ?':'Download scenario CSV ?';$('metrics').innerHTML=real?`<div class="metric"><span class="value">${healthsites?.features.length??'—'}</span><span class="label">Archived mapped facilities</span></div><div class="metric"><span class="value">${escape(c.city)}</span><span class="label">Geographic coverage only</span></div><div class="metric"><span class="value">ODbL</span><span class="label">OpenStreetMap attribution</span></div><div class="metric"><span class="value">No link</span><span class="label">To synthetic risk or funding</span></div>`:`<div class="metric"><span class="value">${r.indoor_c.toFixed(1)}°C</span><span class="label">Synthetic indoor temperature</span></div><div class="metric"><span class="value">${c.coastal?(r.access_open?'Open':'Closed'):'Inland'}</span><span class="label">Conceptual marine access</span></div><div class="metric"><span class="value">${r.capacity}<small> / ${c.daily_visits}</small></span><span class="label">Toy visit capacity / demand</span></div><div class="metric"><span class="value">${r.unmet_visits}</span><span class="label">Unmet visits in toy model</span></div>`;
 $('tour').hidden=state.view!=='tour';if(state.view==='tour'){const t=tour[state.step];$('tour-step').textContent=`STOP ${state.step+1} OF ${tour.length}`;$('tour-title').textContent=t.title;$('tour-text').textContent=t.text;$('previous').disabled=state.step===0;$('next').disabled=state.step===tour.length-1;}
 $('compare').hidden=state.view!=='adapt';$('plot').hidden=true;$('map').toggleAttribute('hidden',state.view==='adapt');$('map-buttons').hidden=state.view==='adapt'||state.view==='map3d'||state.view==='scene';
 $('visual-title').textContent=real?'Archived Healthsites facilities':state.view==='scene'?`${c.city}: a conceptual coastal clinic`:state.view==='adapt'?`${c.city}: adaptation comparison`:state.view==='map3d'?'Extruded scenario map':'Geographic context';$('visual-subtitle').textContent=real?'Observed map features, not verified facility services':'SYNTHETIC · no real facility locations or funding';
 $('legend').innerHTML=real?'<span><i style="background:#376a98"></i>Archived Healthsites / OSM point</span>':state.layer==='heat'?'<span><i style="background:#cfab58"></i>Below 35 °C</span><span><i style="background:#bb6039"></i>35 °C or more</span><span>Teaching threshold, not a clinical threshold</span>':state.layer==='access'?'<span><i style="background:#177a66"></i>Open / inland</span><span><i style="background:#c46535"></i>Closed coastal route</span>':'<span><i style="background:#b6573d"></i>0–39 visits</span><span><i style="background:#b49a50"></i>40–69 visits</span><span><i style="background:#247b68"></i>70+ visits</span>';
 if(state.view==='scene'&&!real)$('legend').innerHTML='<span><i style="background:#429cba"></i>Conceptual water plane</span><span><i style="background:#838c8d"></i>Access route</span><span><i style="background:#458574"></i>Clinic / shade</span>';if(state.view==='adapt'&&!real)$('legend').innerHTML='<span><i style="background:#12665d"></i>Synthetic capacity, visits per fictional day</span>';$('explanation').innerHTML=real?'<p>Archived public map features from Healthsites / OpenStreetMap. Completeness, names, service availability and current operation are unverified. None is marked as PEPFAR-supported. The heat, water and adaptation controls apply only to the separate fictional scenario layer.</p><p>© OpenStreetMap contributors, ODbL. <a href="../book/data-and-methods/">Snapshot provenance and limitations</a> · <a href="https://www.openstreetmap.org/copyright">License and attribution</a></p>':`<p><strong>${escape(c.city)}, ${escape(c.country)}:</strong> invented water supply supports ${(100*r.water_fraction).toFixed(0)}% and electricity supports ${(100*r.power_fraction).toFixed(0)}% of the assumed day before the heat and access factors. ${c.coastal?`Road elevation is ${r.road_m.toFixed(2)} m; clinic floor is ${c.floor_m.toFixed(2)} m above an invented common datum.`:'Marine water is ignored for this inland context; rainfall flooding is not modeled.'}</p><p>No hydrologic connectivity, waves, tides, drainage, land motion, clinical outcomes or conflict probabilities are computed. These are conditional teaching comparisons, not forecasts.</p>`;
 $('view-status').textContent='Bundled geographic data loaded. No external basemap tiles are required.';if(real&&!healthsites)$('view-status').textContent='Healthsites snapshot is unavailable. Choose a synthetic layer; source and archive details remain in the Book.';
 if(state.view==='adapt')renderComparison();else if((state.view==='map3d'||state.view==='scene')&&!real)render3D(rows,version);else renderMap(rows);table(rows);
 const params=new URLSearchParams({view:state.view,case:state.case,heat:state.heat,water:state.water,adaptation:state.adaptation,layer:state.layer,step:state.step});if(new URLSearchParams(location.search).get('webgl')==='off')params.set('webgl','off');history.replaceState(null,'',`?${params}`);
 }catch(e){$('view-status').textContent=`Unable to apply scenario: ${e.message}`;$('view-status').classList.add('error');}}
function download(text,name,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function startTour(step){state.step=Math.max(0,Math.min(tour.length-1,step));Object.assign(state,tour[state.step]);state.view='tour';state.layer='capacity';syncControls();update();}
async function initialize(){try{[cases,adaptations,land]=await Promise.all([json('../data/cases.json'),json('../data/adaptations.json'),json('../data/natural-earth-land.geojson')]);try{healthsites=await json('../data/healthsites_facilities.geojson');}catch{}
 $('case').innerHTML=cases.map(c=>`<option value="${c.id}">${escape(c.city)} · ${escape(c.country)}</option>`).join('');$('adaptation').innerHTML=Object.entries(adaptations).map(([k,a])=>`<option value="${k}">${escape(a.label)}</option>`).join('');
 const q=new URLSearchParams(location.search);const step=Number(q.get('step'));if(q.has('step')&&Number.isInteger(step)&&step>=0&&step<tour.length)state.step=step;if(cases.some(c=>c.id===q.get('case')))state.case=q.get('case');if(['map','map3d','scene','adapt','tour'].includes(q.get('view')))state.view=q.get('view');if(['capacity','heat','access','healthsites'].includes(q.get('layer')))state.layer=q.get('layer');if(Object.hasOwn(adaptations,q.get('adaptation')))state.adaptation=q.get('adaptation');for(const [key,max]of[['heat',5],['water',3]]){const v=Number(q.get(key));if(q.has(key)&&Number.isFinite(v)&&v>=0&&v<=max)state[key]=v;}
 syncControls();for(const id of['case','layer','adaptation'])$(id).addEventListener('change',()=>{state[id]=$(id).value;update();});for(const id of['heat','water'])$(id).addEventListener('input',()=>{state[id]=Number($(id).value);update();});document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;if(state.view==='tour')startTour(state.step);else update();}));
 $('reset').onclick=()=>{Object.assign(state,{case:'mumbai',heat:1.5,water:.6,adaptation:'baseline',layer:'capacity',step:0,zoom:1});syncControls();update();};$('zoom-in').onclick=()=>{state.zoom=Math.min(8,state.zoom*1.6);update();};$('zoom-out').onclick=()=>{state.zoom=Math.max(1,state.zoom/1.6);update();};$('zoom-reset').onclick=()=>{state.zoom=1;update();};$('previous').onclick=()=>startTour(state.step-1);$('next').onclick=()=>startTour(state.step+1);
 $('csv').onclick=()=>{if(state.layer==='healthsites'){if(!healthsites)return;const fields=['osm_id','osm_type','name','amenity','healthcare','context_city','country','data_type','source','license','longitude','latitude','original_extract_date'];const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const lines=facilityFeatures().map(f=>{const r={...f.properties,longitude:f.geometry.coordinates[0],latitude:f.geometry.coordinates[1],original_extract_date:'Unknown; archived source'};return fields.map(k=>quote(r[k])).join(',');});download(fields.map(quote).join(',')+'\n'+lines.join('\n')+'\n','healthsites-'+state.case+'-archived.csv','text/csv;charset=utf-8');return;}const r=scenario(selected(),state.heat,state.water,state.adaptation,adaptations);r.model='healthlab-v1';r.units='Celsius; metres invented datum; visits per fictional day; arbitrary cost';r.source='Original synthetic teaching scenario CC0';r.limitation='Not observations or forecasts or real facility funding';const quote=v=>`"${String(v).replaceAll('"','""')}"`;download(Object.keys(r).map(quote).join(',')+'\n'+Object.values(r).map(quote).join(',')+'\n','climate-health-synthetic-scenario.csv','text/csv;charset=utf-8');};
 $('story-export').onclick=async()=>{try{const real=state.layer==='healthsites';if(real&&!healthsites)return;const project=await json(real?'../projects/healthsites-context.jGIS':'../projects/climate-health.jGIS');if(real)project.metadata.selectedContext=JSON.stringify({case_id:state.case,data_type:'archived_osm',source_date:'Unknown',license:'ODbL-1.0'});else project.metadata.exportedScenario=JSON.stringify(scenario(selected(),state.heat,state.water,state.adaptation,adaptations));project.metadata.exportNote='Save in content/projects beside the bundled ../data directory. Preserve source-specific data labels and licenses.';project.stories['climate-health'].title=`${selected().city}: ${real?'archived facility context':'my climate-health scenario'}`;download(JSON.stringify(project,null,2),'my-climate-health.jGIS','application/json');$('view-status').textContent='Story project downloaded. Save it in projects/ with the bundled sibling data/ folder; the selected assumptions are recorded in project metadata.';}catch(e){$('view-status').textContent=`Story export failed: ${e.message}`;}};
 $('quiz-check').onclick=()=>{const chosen=[...document.querySelectorAll('[name=quiz]:checked')].map(x=>x.value);const right=chosen.length===2&&chosen.includes('arithmetic')&&chosen.includes('dependency');$('quiz-feedback').textContent=right?'Correct. Transparent comparisons can help identify questions and dependencies. They cannot establish real funding or predict disease.':'Reconsider the evidence: choose comparisons under stated assumptions and a dependency to investigate. Country disease forecasts and real funding claims require different evidence.';};update();
 }catch(e){$('view-status').textContent=`Data failed to load: ${e.message}. Reload the page or read the Book data reference. Serve this site over HTTP, not file://.`;$('view-status').classList.add('error');}}
initialize();
